trigger: none
pool:
  name: rajendhar-ado ## Agent pool name (self hosted); Azure Pipelines is the Azure pipeline its free

# !!!!!! HANDLE WITH CARE!!!!!!!!!!!

# Stage 1 : in the below stage the It will destory the infrastracure
stages:
- stage: terraformValidation
  displayName: 'ValidateTerraform' # Pipeline Stage name.
  jobs:
  - job: terraformValidate
    steps:
    - task: TerraformInstaller@1 # It will install terraform latest version.
      displayName: 'InstallTerraformlatest'
    - task: TerraformTaskV4@4
      displayName: 'Terraform : init' # Task display name
      inputs:
        command: init # terraform command that will be execute.
        workingDirectory: $(System.DefaultWorkingDirectory)/rajendhar-project01/Project01-Demo/10_ResourceCode # Path of the code in repo.
        backendServiceArm: 'rajendhar-sc' # Service connection name in Azure ADO.
        backendAzureRmResourceGroupName: rajendhar-rg # Resource Group Name where tfstatefile saved.
        backendAzureRmStorageAccountName: rajendharprojectstate # Storage account name where tfstatefile saved.
        backendAzureRmContainerName: statefiles # Storage container name where tfstatefile saved.
        backendAzureRmKey: 'resource-group.tfstate' # tfstate file name.
    - task: TerraformTaskV4@4
      displayName: 'Terraform : validate'
      inputs:
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/rajendhar-project01/Project01-Demo/10_ResourceCode
        environmentServiceNameAzureRM: 'rajendhar-sc'
        backendAzureRmResourceGroupName: rajendhar-rg
        backendAzureRmStorageAccountName: rajendharprojectstate
        backendAzureRmContainerName: statefiles
        backendAzureRmKey: 'resource-group.tfstate' 

- stage: terraformapply
  displayName: 'applyTerraform'
  jobs:
  - deployment: terraformapply
    timeoutInMinutes: 0
    displayName: Provision infrastructure
    environment: "Deployment"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformInstaller@1
            displayName: 'InstallTerraformlatest'
          - task: TerraformTaskV4@4
            displayName: 'Terraform : init'
            inputs:
              command: init
              workingDirectory: $(System.DefaultWorkingDirectory)/rajendhar-project01/Project01-Demo/10_ResourceCode
              backendServiceArm: 'rajendhar-sc'
              backendAzureRmResourceGroupName: rajendhar-rg
              backendAzureRmStorageAccountName: rajendharprojectstate
              backendAzureRmContainerName: statefiles
              backendAzureRmKey: 'resource-group.tfstate'

          - task: TerraformTaskV4@4
            displayName: 'Terraform : destroy'
            inputs:
              command: destroy
              workingDirectory: $(System.DefaultWorkingDirectory)/rajendhar-project01/Project01-Demo/10_ResourceCode
              environmentServiceNameAzureRM: 'rajendhar-sc'
              backendAzureRmResourceGroupName: rajendhar-rg
              backendAzureRmStorageAccountName: rajendharprojectstate
              backendAzureRmContainerName: statefiles
              backendAzureRmKey: 'resource-group.tfstate'            
